<?php

declare(strict_types=1);

namespace Devscast\AirtelMoney\Data;

/**
 * Class UssdPaymentTransaction
 * @package Devscast\AirtelMoney\Data
 * @author bernard-ng <ngandubernard@gmail.com>
 */
class UssdPaymentTransaction
{
     /**
     * Transaction Id generated by AM
     */
    private string $airtel_money_id;

    /**
     * Partner transaction-id which the partner send in the request
     * Transaction Id generated by TPP / Aggregator / Merchant.
     */
    private ?string $id = null;

    /**
     * Description message for the transaction status
     */
    private ?string $message = null;

    /**
     * Possible Status:
     * TF (Transaction Failed)
     * TS (Transaction Success)
     * TA (Transaction Ambiguous)
     * TIP (Transaction in Progress)
     */
    private string $status;

    /**
     * UssdPaymentTransaction constructor.
     * @param array $data
     * @author bernard-ng <ngandubernard@gmail.com>
     */
    public function __construct(array $data)
    {
        $this->airtel_money_id = $data['airtel_money_id'];
        $this->message = $data['message'] ?: null;
        $this->status = $data['status'];
        $this->id = $data['id'] ?: null;
    }

    /**
     * @author bernard-ng <ngandubernard@gmail.com>
     */
    public function getAirtelMoneyId(): string
    {
        return $this->airtel_money_id;
    }

    /**
     * @author bernard-ng <ngandubernard@gmail.com>
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * @author bernard-ng <ngandubernard@gmail.com>
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * @author bernard-ng <ngandubernard@gmail.com>
     */
    public function getStatus(): string
    {
        return $this->status;
    }
}
