<?php

declare(strict_types=1);

namespace Devscast\AirtelMoney\Data;

class UssdPaymentTransaction
{
     /**
     * Transaction Id generated by AM
     */
    private string $airtel_money_id;

    /**
     * Partner transaction-id which the partner send in the request
     * Transaction Id generated by TPP / Aggregator / Merchant.
     */
    private string $id;

    /**
     * Description message for the transaction status
     */
    private string $message;

    /**
     * Possible Status: 
     * TF (Transaction Failed) 
     * TS (Transaction Success) 
     * TA (Transaction Ambiguous) 
     * TIP (Transaction in Progress)
     */
    private string $status;
}
